import React from 'react'
import Head from 'next/head'
import AppLayout from '../components/AppLayout'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <AppLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          Hello MYME
        </main>
      </div>
    </AppLayout>
  )
}

export default Home